name: CI Stage 1 — tests then push to ACR (branch: testing)

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "testing" ]

env:
  IMAGE_NAME: sit722-backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install deps (backend)
        working-directory: backend
        run: npm install --no-fund --no-audit
      - name: Run unit tests (backend)
        working-directory: backend
        run: npm test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Azure login (SP JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}
      - name: Build & push backend image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG ./backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:$IMAGE_TAG
