name: CI Stage 2

on:
  workflow_run:
    workflows: ["CI Stage 1"]
    types: [completed]

jobs:
  staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'testing' }}
    runs-on: ubuntu-latest
    env:
      RG: rg-sit722-10d
      LOCATION: australiaeast
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      IMAGE_REPO: sit722-backend
      TAG: ${{ github.event.workflow_run.head_sha }}
      DNS_LABEL: sit722stg-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure ACI provider is registered
        run: |
          az provider register -n Microsoft.ContainerInstance --wait || true
          az provider show -n Microsoft.ContainerInstance --query registrationState -o tsv

      - name: Enable ACR admin & fetch creds
        run: |
          set -euo pipefail
          az acr update -n "$ACR_NAME" --admin-enabled true
          echo "ACR_USER=$(az acr credential show -n "$ACR_NAME" --query username -o tsv)" >> $GITHUB_ENV
          echo "ACR_PASS=$(az acr credential show -n "$ACR_NAME" --query passwords[0].value -o tsv)" >> $GITHUB_ENV

      - name: Create ACI staging container (Linux)
        run: |
          set -euo pipefail
          echo "Creating $DNS_LABEL in $LOCATION from $ACR_LOGIN_SERVER/$IMAGE_REPO:$TAG"
          az container create \
            -g "$RG" -l "$LOCATION" \
            -n "$DNS_LABEL" \
            --os-type Linux \
            --image "$ACR_LOGIN_SERVER/$IMAGE_REPO:$TAG" \
            --cpu 1 --memory 1 \
            --ip-address Public --ports 3000 \
            --dns-name-label "$DNS_LABEL" \
            --registry-login-server "$ACR_LOGIN_SERVER" \
            --registry-username "$ACR_USER" \
            --registry-password "$ACR_PASS" \
            --restart-policy Never

          echo "Waiting for Running (manual poll)..."
          for i in {1..40}; do
            STATE=$(az container show -g "$RG" -n "$DNS_LABEL" --query instanceView.state -o tsv || echo unknown)
            echo "State: $STATE"
            if [ "$STATE" = "Running" ]; then break; fi
            sleep 5
          done

          FQDN=$(az container show -g "$RG" -n "$DNS_LABEL" --query ipAddress.fqdn -o tsv)
          echo "FQDN=$FQDN" >> $GITHUB_ENV
          echo "Staging URL: http://$FQDN:3000"

      - name: Health check (/healthz)
        run: |
          set -euo pipefail
          for i in {1..30}; do
            if curl -fsS "http://$FQDN:3000/healthz"; then
              echo "Health check passed"
              exit 0
            fi
            echo "Attempt $i failed; retrying..."
            sleep 5
          done
          echo "Health check failed"; exit 1

      - name: Teardown staging
        if: always()
        run: |
          az container delete -g "$RG" -n "$DNS_LABEL" --yes || true
