name: CI Stage 2

on:
  workflow_run:
    workflows: ["CI Stage 1"]
    types: [completed]

jobs:
  staging:
    # only run after CI Stage 1 succeeded on the 'testing' branch
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'testing' }}
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.ACR_NAME }}
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      IMAGE_REPO: sit722-backend
      TAG: ${{ github.event.workflow_run.head_sha }}

    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Enable ACR admin & docker login
        run: |
          set -euo pipefail
          az acr update -n "$ACR_NAME" --admin-enabled true
          USER=$(az acr credential show -n "$ACR_NAME" --query username -o tsv)
          PASS=$(az acr credential show -n "$ACR_NAME" --query passwords[0].value -o tsv)
          echo "$PASS" | docker login "$ACR_LOGIN_SERVER" -u "$USER" --password-stdin

      - name: Pull image from ACR
        run: docker pull "$ACR_LOGIN_SERVER/$IMAGE_REPO:$TAG"

      - name: Start staging container (ephemeral)
        run: |
          docker run -d --rm --name staging -p 3000:3000 "$ACR_LOGIN_SERVER/$IMAGE_REPO:$TAG"
          echo "Staging URL: http://localhost:3000"
          # small warm-up
          sleep 5

      - name: Health check (/healthz)
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:3000/healthz; then
              echo "Health check passed"
              exit 0
            fi
            echo "Attempt $i failed; retrying..."
            sleep 2
          done
          echo "--- Last 100 container logs ---"
          docker logs --tail=100 staging || true
          exit 1

      - name: Teardown staging
        if: always()
        run: docker stop staging || true
