name: CI Stage 2

on:
  workflow_run:
    workflows: ["CI Stage 1"]
    types: [completed]

jobs:
  staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'testing' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure login (for ACR)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Pull image from ACR
        env:
          ACR: ${{ secrets.ACR_LOGIN_SERVER }}
          TAG: ${{ github.event.workflow_run.head_sha }}
        run: docker pull "$ACR/sit722-backend:$TAG"

      - name: Start staging container (ephemeral)
        id: run
        env:
          ACR: ${{ secrets.ACR_LOGIN_SERVER }}
          TAG: ${{ github.event.workflow_run.head_sha }}
        run: |
          docker run -d --rm --name staging -p 3000:3000 "$ACR/sit722-backend:$TAG"
          echo "Staging URL: http://localhost:3000"
          sleep 5

      - name: Health check (/healthz)
        run: |
          for i in {1..30}; do
            if curl -fsS http://localhost:3000/healthz; then
              echo "Health check passed"
              exit 0
            fi
            echo "Attempt $i failed; retrying..."
            sleep 2
          done
          echo "Health check failed"; exit 1

      - name: Teardown staging
        if: always()
        run: docker stop staging || true
